# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$install = <<SCRIPT
echo ====> Updating Packages
export DEBIAN_FRONTEND=noninteractive
# -qq is pointless, it doesn't work :S
apt-get update > /dev/null
echo ====> Installing Packages
apt-get install -qq -y --no-install-recommends docker.io openvswitch-switch unzip
ln -s /vagrant/scripts/socketplane.sh /usr/bin/socketplane
cd /usr/bin
wget --quiet https://dl.bintray.com/mitchellh/consul/0.4.1_linux_amd64.zip
unzip *.zip
rm *.zip
cd /vagrant && docker build -q -t socketplane/socketplane . > /dev/null
echo ====> Installing SocketPlane
socketplane install unattended
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.define "cloud1" do |cloud1|
    cloud1.vm.box = "socketplane/ubuntu-14.10"
    cloud1.vm.hostname = "cloud1"
    cloud1.vm.synced_folder "../../", "/vagrant"
    cloud1.vm.network :private_network, ip: "10.31.254.10"
    cloud1.vm.provision :shell, inline: "echo 'export BOOTSTRAP=true' >> ~/.profile"
    cloud1.vm.provision :shell, inline: $install
 end
  config.vm.define "cloud2" do |cloud2|
    cloud2.vm.box = "socketplane/ubuntu-14.10"
    cloud2.vm.hostname = "cloud2"
    cloud2.vm.synced_folder "../../", "/vagrant"
    cloud2.vm.network :private_network, ip: "172.31.254.10"
    cloud2.vm.provision :shell, inline: "echo 'export BOOTSTRAP=false' >> ~/.profile"
    cloud2.vm.provision :shell, inline: $install
  end
end
